# -*- coding: utf-8 -*-
"""FinalSSPdel.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10pk-ClwS8WDE5IqqvIQhKcGC4IeNS1Ie
"""

# -------------------------------
# Import required libraries
# -------------------------------
import random
import pandas as pd
import json

# -------------------------------
# Required data for user generation
# -------------------------------
indian_names = [
    "Rahul", "Priya", "Amit", "Neha", "Arjun", "Riya", "Vikas", "Kabir",
    "Sneha", "Rohan", "Isha", "Kunal", "Pooja", "Sanjay", "Maya"
]

locations = [
    "Delhi", "Mumbai", "Bangalore", "Hyderabad", "Chennai",
    "Pune", "Kolkata", "Ahmedabad"
]

# -------------------------------
# Step 1: Define users (Guarantee at least one duplicate)
# -------------------------------
duplicate_name = random.choice(indian_names)

num_users = 5
users = []

# Two users with the same name
users.append({
    "user_id": 101,
    "username": duplicate_name,
    "location": random.choice(locations)
})
users.append({
    "user_id": 102,
    "username": duplicate_name,
    "location": random.choice(locations)
})

# Remaining 3 users
for i in range(103, 100 + num_users + 1):
    users.append({
        "user_id": i,
        "username": random.choice(indian_names),
        "location": random.choice(locations)
    })

# Mapping
user_map = {u["user_id"]: u for u in users}

# -------------------------------
# Step 3: Engagement weights & max values
# -------------------------------
weights = {"likes":0.1, "comments":0.2, "messages":0.4, "story_views":0.3}
max_values = {"likes":20, "comments":10, "messages":25, "story_views":15}

# -------------------------------
# Step 4: Generate connections
# -------------------------------
records = []
for u in users:
    num_friends = random.randint(1, num_users - 1)
    friend_candidates = [f for f in users if f["user_id"] != u["user_id"]]
    friends = random.sample(friend_candidates, num_friends)

    for f in friends:
        likes = random.randint(0, max_values["likes"])
        comments = random.randint(0, max_values["comments"])
        messages = random.randint(0, max_values["messages"])
        story_views = random.randint(0, max_values["story_views"])

        likes_norm = likes / max_values["likes"]
        comments_norm = comments / max_values["comments"]
        messages_norm = messages / max_values["messages"]
        story_views_norm = story_views / max_values["story_views"]

        engagement_score = (
            weights["likes"]*likes_norm +
            weights["comments"]*comments_norm +
            weights["messages"]*messages_norm +
            weights["story_views"]*story_views_norm
        )

        # Bonus if locations match
        if u["location"] == f["location"]:
            engagement_score = min(engagement_score * 1.1, 1.0)

        record = {
            "user_id": u["user_id"],
            "username": u["username"],
            "friend_id": f["user_id"],
            "friend_name": f["username"],
            "location": u["location"],
            "friend_location": f["location"],
            "likes": likes,
            "comments": comments,
            "messages": messages,
            "story_views": story_views,
            "engagement_score": round(engagement_score, 3),
            "edge_weight": round(1 - engagement_score, 3)
        }
        records.append(record)

# -------------------------------
# Step 5: Save dataset
# -------------------------------
df = pd.DataFrame(records)
df.to_csv("social_engagement_5_users.csv", index=False)
with open("social_engagement_5_users.json", "w") as f:
    json.dump(records, f, indent=4)

print("✅ Dataset created successfully!")
print("CSV File: social_engagement_5_users.csv")
print("JSON File: social_engagement_5_users.json")

df.head(10)

"""## **Code**"""

import math
from enum import Enum
from collections import deque, namedtuple
import networkx as nx
import matplotlib.pyplot as plt
from IPython.display import display # Import the display function
import pandas as pd
import random
import time
import heapq # For static Dijkstra

# Define a small tolerance for floating-point comparisons
FLOAT_TOLERANCE = 1e-9

# ---------------------------------
# 1. SSSP-Del Algorithm Definitions
# ---------------------------------

class MessageType(Enum):
    DISTANCE_UPDATE = "DistanceUpdate"
    SET_TO_INFINITY = "SetToInfinity"
    DISTANCE_QUERY = "DistanceQuery"
    ADD_TO_SUCCESSOR = "AddToSuccessor"
    REMOVE_FROM_SUCCESSOR = "RemoveFromSuccessor"

Message = namedtuple('Message', ['from_id', 'to_id', 'type', 'body'])

class User:
    """Represents a Vertex (a user) in the content network."""
    def __init__(self, user_id, username, location):
        self.id = user_id
        self.username = username
        self.location = location

        self.distance = math.inf
        self.predecessor = None
        self.successors = set()
        self.marked_as_infinity = False

        self.out_edges = {} # Key: to_id, Value: weight
        self.in_edges = {}  # Key: from_id, Value: weight

    def __repr__(self):
        pred_id = self.predecessor if self.predecessor else 'None'
        # Display with more precision for debugging
        dist = 'inf' if self.distance == math.inf else round(self.distance, 4)
        return f"  User(ID: {self.id}) | Cost: {dist} | Pred: {pred_id} | Successors: {self.successors}"

    def reset_sssp(self):
        """Resets the SSSP state for a new source calculation."""
        self.distance = math.inf
        self.predecessor = None
        self.successors = set()
        self.marked_as_infinity = False

    def on_message(self, msg, message_queue, all_users):
        """Main logic handler for all incoming messages."""

        if msg.type == MessageType.DISTANCE_UPDATE:
            new_distance = msg.body['distance']

            # --- MODIFIED: Use tolerance for float comparison ---
            # Check if new_distance is significantly smaller than current distance
            if new_distance < (self.distance - FLOAT_TOLERANCE):
                # print(f"    V({self.id}): Received better path! Old Cost:{self.distance}, New Cost:{new_distance} from V({msg.from_id})")
                if self.predecessor:
                    # Ensure predecessor exists before sending message
                    if self.predecessor in all_users:
                        message_queue.append(Message(self.id, self.predecessor, MessageType.REMOVE_FROM_SUCCESSOR, {}))
                self.distance = new_distance
                self.predecessor = msg.from_id
                # Ensure predecessor exists before sending message
                if self.predecessor in all_users:
                    message_queue.append(Message(self.id, self.predecessor, MessageType.ADD_TO_SUCCESSOR, {}))

                for friend_id, weight in self.out_edges.items():
                    if friend_id != self.predecessor:
                        # Ensure friend exists before sending message
                        if friend_id in all_users:
                             message_queue.append(Message(self.id, friend_id, MessageType.DISTANCE_UPDATE, {'distance': self.distance + weight}))


        elif msg.type == MessageType.SET_TO_INFINITY:
            # Check if already processed OR if distance is already inf
            if self.marked_as_infinity or self.distance == math.inf :
                return

            print(f"    V({self.id}): Path invalidated by V({msg.from_id}). Setting cost to 'inf'.")
            self.distance = math.inf
            # Store the invalidator temporarily for debugging? No, just clear predecessor
            self.predecessor = None
            self.marked_as_infinity = True

            # --- Propagate invalidation ---
            successors_to_notify = list(self.successors) # Copy successors before clearing
            self.successors.clear() # Clear immediately after copying

            for successor_id in successors_to_notify:
                 # Ensure successor exists before sending message
                 if successor_id in all_users:
                     # Check if the path was indeed through this node before invalidating
                     successor_node = all_users.get(successor_id)
                     if successor_node and successor_node.predecessor == self.id:
                          message_queue.append(Message(self.id, successor_id, MessageType.SET_TO_INFINITY, {}))

        elif msg.type == MessageType.DISTANCE_QUERY:
            if self.distance != math.inf:
                # Check if we have an edge *to* the querier (since graph is directed)
                weight_to_querier = self.out_edges.get(msg.from_id)
                if weight_to_querier is not None:
                     # Ensure querier exists before sending message
                     if msg.from_id in all_users:
                         # Offer the querier a path via this edge
                         message_queue.append(Message(self.id, msg.from_id, MessageType.DISTANCE_UPDATE, {'distance': self.distance + weight_to_querier}))


        elif msg.type == MessageType.ADD_TO_SUCCESSOR:
            # Check if sender exists before adding
            if msg.from_id in all_users:
                 self.successors.add(msg.from_id)

        elif msg.type == MessageType.REMOVE_FROM_SUCCESSOR:
            self.successors.discard(msg.from_id)


class SSSPGraph:
    """Manages the graph, users, and the message queue for the SSSP-Del algorithm."""
    def __init__(self):
        self.all_users = {} # user_id -> User object
        self.message_queue = deque()
        self.source_user_id = None

    def load_users_from_df(self, df):
        """Initializes all User objects from the dataframe."""
        # Consolidate user details first
        user_details = {}
        for _, row in df.iterrows():
            # Use .get() for safer access
            uid = row.get('user_id')
            fid = row.get('friend_id')
            uname = row.get('username')
            fname = row.get('friend_name')
            uloc = row.get('location')
            floc = row.get('friend_location')

            # Ensure IDs are treated as integers
            try:
                uid_int = int(uid) if pd.notna(uid) else None
                fid_int = int(fid) if pd.notna(fid) else None
            except (ValueError, TypeError):
                print(f"Warning: Skipping row with non-integer IDs: {uid}, {fid}")
                continue


            if uid_int is not None and uid_int not in user_details:
                user_details[uid_int] = {'username': uname, 'location': uloc}
            if fid_int is not None:
                 # Check if friend details are already captured
                if fid_int not in user_details:
                    # Make sure fname and floc exist before assigning
                    details_to_add = {}
                    if pd.notna(fname): details_to_add['username'] = fname
                    if pd.notna(floc): details_to_add['location'] = floc
                    user_details[fid_int] = details_to_add


        # Create User objects using consolidated details
        all_ids = set()
        if 'user_id' in df.columns:
             # Use .dropna().astype(int).unique() for robust ID extraction
            all_ids.update(df['user_id'].dropna().astype(int).unique())
        if 'friend_id' in df.columns:
            all_ids.update(df['friend_id'].dropna().astype(int).unique())


        for user_id in all_ids:
             try:
                 user_id_int = int(user_id) # Should already be int from unique()
                 if user_id_int not in self.all_users:
                     details = user_details.get(user_id_int, {}) # Use empty dict as default
                     uname = details.get('username', f'user_{user_id_int}')
                     uloc = details.get('location', 'N/A')
                     self.all_users[user_id_int] = User(user_id_int, uname if pd.notna(uname) else f'user_{user_id_int}', uloc if pd.notna(uloc) else 'N/A')
             except (ValueError, TypeError):
                 print(f"Warning: Skipping invalid user ID {user_id} during User object creation.")

        print(f"Loaded {len(self.all_users)} unique users.")

    def find_user_by_name(self, username):
        """
        Find the closest user (by SSSP distance from the active source) that has the given username.
        Returns a triple: (user_id_or_None, distance_or_math.inf, path_or_None)

        Behavior:
         - case-insensitive name matching
         - if a match is reachable in the current SSSP tree, pick the match with minimal SSSP distance
           and return its SSSP path (uses get_sssp_path_list()).
         - if none of the matches are reachable, fall back to running static Dijkstra (run_static_p2p_path)
           from the current source to each matching user and pick the closest one.
         - if no matches at all, returns (None, math.inf, None)
         - if source is not set, prints an error and returns (None, math.inf, None)
        """
        if not username or not isinstance(username, str):
            return None, math.inf, None

        # Case-insensitive match
        target_name = username.strip().lower()
        matches = [uid for uid, u in self.all_users.items()
                   if isinstance(u.username, str) and u.username.strip().lower() == target_name]

        if not matches:
            # No user with that exact name
            return None, math.inf, None

        if not self.source_user_id:
            print("Error: No active source set. Use 'source <id>' before searching by name.")
            return None, math.inf, None

        # Prefer matches reachable in the SSSP tree (fast)
        reachable_matches = [(uid, self.all_users[uid].distance) for uid in matches
                             if self.all_users[uid].distance != math.inf]

        if reachable_matches:
            # pick minimal distance
            best_uid, best_dist = min(reachable_matches, key=lambda x: x[1])
            best_path = self.get_sssp_path_list(best_uid)
            return best_uid, best_dist, best_path

        # Fallback: none reachable via current SSSP tree — run static point-to-point Dijkstra to each match
        best_uid = None
        best_dist = math.inf
        best_path = None

        for uid in matches:
            d_time, path, dist = run_static_p2p_path(self.all_users, self.source_user_id, uid)
            # We only care about distance/path, ignore d_time here
            if dist != math.inf and dist < best_dist:
                best_dist = dist
                best_uid = uid
                best_path = path

        if best_uid is not None:
            return best_uid, best_dist, best_path

        # No reachable match at all
        # return the first matching uid (unreachable) to indicate existence
        return matches[0], math.inf, None

    def load_edges_from_df(self, df):
        """Builds the initial graph from the dataframe."""
        edge_count = 0
        skipped_count = 0
        for _, row in df.iterrows():
             # Ensure IDs and weight are valid numbers
            try:
                u_id = int(row['user_id'])
                v_id = int(row['friend_id'])
                weight = float(row['edge_weight'])
                # Validate weight range AND ensure it's not exactly zero unless intended
                if not (FLOAT_TOLERANCE <= weight <= 1.0):
                     if weight < FLOAT_TOLERANCE and weight >= 0: # Allow near-zero weights
                          pass # Keep it
                     else:
                          print(f"Warning: Invalid edge weight {weight} for {u_id}->{v_id}. Skipping.")
                          skipped_count += 1
                          continue
            except (ValueError, TypeError, KeyError):
                print(f"Warning: Skipping edge with invalid data: {row.get('user_id')} -> {row.get('friend_id')}")
                skipped_count += 1
                continue

            u = self.all_users.get(u_id)
            v = self.all_users.get(v_id)

            if u and v:
                # Debug print for edge loading
                # print(f"    Loading edge: {u_id} -> {v_id} with weight {weight:.4f}")
                u.out_edges[v.id] = weight
                v.in_edges[u.id] = weight
                edge_count += 1
            else:
                 print(f"Warning: User {u_id} or {v_id} not found when loading edge. Skipping.")
                 skipped_count += 1


        print(f"Loaded {edge_count} edges into the graph. Skipped {skipped_count} edges.")

    def set_source(self, source_user_id):
        """Sets a new source user and runs a full SSSP-Del from scratch."""
        if source_user_id not in self.all_users:
            print(f"Error: User ID {source_user_id} not found in graph.")
            return 0.0 # Return 0 time for error

        print(f"\n--- Setting new source to {source_user_id} and running initial SSSP-Del ---")
        self.source_user_id = source_user_id

        # Reset SSSP state for all users
        for user in self.all_users.values():
            user.reset_sssp()

        # Set source distance and propagate
        source = self.all_users.get(self.source_user_id)
        if source: # Check if source exists
             source.distance = 0
        else:
             print(f"Error: Source user {source_user_id} somehow not found after check.")
             return 0.0 # Indicate error

        self.message_queue.clear()
        # Propagate from source only if it exists
        if source:
            for friend_id, weight in source.out_edges.items():
                 # Check if friend_id exists before sending message
                 if friend_id in self.all_users:
                     self.message_queue.append(Message(source.id, friend_id, MessageType.DISTANCE_UPDATE, {'distance': weight}))

        start_time = time.perf_counter()
        self.process_queue()
        end_time = time.perf_counter()

        print("--- Initial SSSP-Del complete. Shortest path tree is built. ---")
        return end_time - start_time

    def process_queue(self):
        """Simulates processing all SSSP-Del messages until convergence."""
        #print(f"  --- Processing {len(self.message_queue)} messages ---")
        i = 0
        processed_count = 0
        # More robust failsafe, check queue length too
        max_messages = len(self.all_users) * len(self.all_users) * 5
        while self.message_queue:
            if i > max_messages:
                 print(f"  --- Hit processing limit of {i} messages, stopping. Queue size: {len(self.message_queue)} ---")
                 # Print some messages from the queue for debugging
                 for _ in range(min(5, len(self.message_queue))):
                     print(f"      Sample pending msg: {self.message_queue[_]}")
                 break
            i += 1
            msg = self.message_queue.popleft()
            receiver = self.all_users.get(msg.to_id)
            if receiver:
                receiver.on_message(msg, self.message_queue, self.all_users)
                processed_count += 1
        #print(f"  --- Message queue empty after {processed_count} messages processed. System converged. ---")

    def simulate_edge_add(self, u_id, v_id, weight):
        """Simulates an 'Edge Addition' and runs the SSSP-Del update."""
        print(f"\n>>> DYNAMIC CHANGE: ADD_EDGE({u_id} -> {v_id}, weight={weight})")

        for user_id in [u_id, v_id]:
            if user_id not in self.all_users:
                print(f"Error: User {user_id} not found.")
                return 0.0

        # Validate weight
        if not (FLOAT_TOLERANCE <= weight <= 1.0):
             if weight < FLOAT_TOLERANCE and weight >= 0: # Allow near-zero weights
                 pass
             else:
                 print(f"Error: Invalid weight {weight}. Must be between 0 and 1.")
                 return 0.0


        u = self.all_users[u_id]
        v = self.all_users[v_id]

        u.out_edges[v_id] = weight
        v.in_edges[u_id] = weight
        print(f"    Added edge {u_id}->{v_id}. u.out_edges: {list(u.out_edges.keys())}")

        # As per Listing 3, check if this new edge creates a shorter path
        start_time = time.perf_counter()
        # This check only works if a source_user_id is set for the benchmark
        # Use tolerance in check
        if self.source_user_id and u.distance != math.inf and (u.distance + weight) < (v.distance - FLOAT_TOLERANCE):
            self.message_queue.append(Message(u_id, v_id, MessageType.DISTANCE_UPDATE, {'distance': u.distance + weight}))
            self.process_queue()

        end_time = time.perf_counter()
        return end_time - start_time

    def simulate_edge_break(self, u_id, v_id):
        """
        Simulates an 'Edge Deletion' and runs the SSSP-Del update.
        This function is now bidirectional.
        """
        print(f"\n>>> DYNAMIC CHANGE: Breaking/Deleting Edge between {u_id} and {v_id}")
        start_time = time.perf_counter()

        # --- Break Edge u -> v ---
        self._break_single_edge(u_id, v_id)
        # --- Break Edge v -> u (if it exists) ---
        self._break_single_edge(v_id, u_id)

        end_time = time.perf_counter()
        return end_time - start_time

    def _break_single_edge(self, u_id, v_id):
        """Internal helper to break a single-direction edge and trigger SSSP-Del."""
        u = self.all_users.get(u_id)
        v = self.all_users.get(v_id)

        if not u or not v or v_id not in u.out_edges:
            print(f"    (Edge {u_id}->{v_id} does not exist or already broken.)")
            return

        # SSSP-Del logic only triggers if a benchmark source is set
        if self.source_user_id:
            # Epoch check needs to happen before state change
             if self.message_queue:
                print("Warning: Message queue not empty before deletion epoch. Processing first.")
                self.process_queue() # Ensure convergence before proceeding
             assert not self.message_queue, "Epoch failed: Queue must be empty before deletion."

        print(f"    Breaking directed edge: {u_id}->{v_id}")
        old_weight = u.out_edges.get(v_id, math.inf) # Get weight before deleting

        # --- MODIFIED: More robust deletion ---
        if v_id in u.out_edges:
            del u.out_edges[v_id]
            print(f"      Removed {v_id} from out_edges of {u_id}. Remaining: {list(u.out_edges.keys())}")
        if u_id in v.in_edges:
            del v.in_edges[u_id]
            print(f"      Removed {u_id} from in_edges of {v_id}. Remaining: {list(v.in_edges.keys())}")

        # SSSP-Del logic only triggers if a benchmark source is set
        if self.source_user_id:
            v_exists = v_id in self.all_users
            u_is_reachable = (u.distance != math.inf)

            # --- MODIFIED: Use math.isclose for checking critical path ---
            # Check if the path was critical *using the old weight*
            # Check if predecessor is u_id before checking distance condition
            is_critical_path = v_exists and v.predecessor == u_id and u_is_reachable
            if is_critical_path:
                 # Now check the distance condition more carefully
                 # Ensure old_weight is valid before comparison
                 if old_weight != math.inf:
                      # Check if u actually exists before accessing its distance
                      if u:
                           is_critical_path = math.isclose(v.distance, u.distance + old_weight, rel_tol=FLOAT_TOLERANCE)
                      else: # Should not happen if u_is_reachable is true
                           is_critical_path = False
                 else:
                      is_critical_path = False # Cannot be critical if weight was inf


            if is_critical_path:
                print(f"    SSSP-Del Path for V({v_id}) was broken! (Old cost: {v.distance:.4f})") # Increased precision

                # --- PHASE 1: Invalidation ---
                print("\n  --- Starting Phase 1: Invalidation ---")
                self.message_queue.append(Message(u_id, v_id, MessageType.SET_TO_INFINITY, {}))
                self.process_queue()

                # --- PHASE 2: Recomputation ---
                print("\n  --- Starting Phase 2: Recomputation ---")
                affected_vertices = []
                for user in self.all_users.values():
                    if user.marked_as_infinity:
                        user.marked_as_infinity = False
                        affected_vertices.append(user)
                print(f"    {len(affected_vertices)} vertices were affected. Querying neighbors...")
                for user in affected_vertices:
                    # Query all *remaining* incoming neighbors
                    for neighbor_id in user.in_edges.keys():
                         # Ensure neighbor exists before querying
                         if neighbor_id in self.all_users:
                             self.message_queue.append(Message(user.id, neighbor_id, MessageType.DISTANCE_QUERY, {}))

                self.process_queue()
            else:
                 # Check why it wasn't critical
                 reason = "unknown" # Default reason
                 if not v_exists: reason = "v does not exist"
                 elif v.predecessor != u_id: reason = f"v's predecessor is {v.predecessor}, not {u_id}"
                 elif not u_is_reachable: reason = f"u ({u_id}) was not reachable"
                 elif u is None: reason = f"u ({u_id}) node object is missing" # Added check
                 elif old_weight == math.inf: reason = "old weight was infinity"
                 # Check distance condition carefully only if u exists
                 elif u and not math.isclose(v.distance, u.distance + old_weight, rel_tol=FLOAT_TOLERANCE):
                      reason = f"distance condition false ({v.distance:.4f} vs {u.distance + old_weight:.4f})"

                 print(f"    Edge {u_id}->{v_id} was deleted, but it was not the SSSP-Del tree's shortest path for V({v_id}). Reason: {reason}. No SSSP-Del changes needed.")

    def simulate_batch_update(self, batch_df):
        """
        --- NOVELTY: Efficient Batched Updates ---
        Processes a batch of additions and deletions together.
        """
        print(f"\n>>> DYNAMIC BATCH CHANGE: Processing {len(batch_df)} events ---")
        if not self.source_user_id:
            print("Error: Please set a source user first with 'source <id>'.")
            return 0.0

        start_time = time.perf_counter()

        # --- 1. Apply all structural changes and collect initial messages ---

        # Ensure queue is empty before starting batch
        if self.message_queue:
            print("Warning: Processing non-empty queue before batch.")
            self.process_queue()
        assert not self.message_queue, "Epoch failed: Queue must be empty before batch."

        initial_add_messages = []
        initial_delete_messages = []
        affected_nodes_from_deletes = set()

        for _, row in batch_df.iterrows():
            op = row.get('operation')
            u_id = int(row.get('u_id'))
            v_id = int(row.get('v_id'))

            u = self.all_users.get(u_id)
            v = self.all_users.get(v_id)
            if not u or not v:
                print(f"    Skipping batch event: User {u_id} or {v_id} not found.")
                continue

            if op == 'add':
                weight = float(row.get('weight'))
                if not (FLOAT_TOLERANCE <= weight <= 1.0):
                     print(f"    Skipping batch add: Invalid weight {weight}.")
                     continue

                print(f"    Batch ADD: {u_id} -> {v_id} (weight={weight})")
                u.out_edges[v_id] = weight
                v.in_edges[u_id] = weight

                # Check if this new edge offers a shortcut
                if u.distance != math.inf and (u.distance + weight) < (v.distance - FLOAT_TOLERANCE):
                    initial_add_messages.append(Message(u_id, v_id, MessageType.DISTANCE_UPDATE, {'distance': u.distance + weight}))

            elif op == 'delete':
                print(f"    Batch DELETE: {u_id} -> {v_id}")

                old_weight = u.out_edges.get(v_id, math.inf)

                if v_id in u.out_edges: del u.out_edges[v_id]
                if u_id in v.in_edges: del v.in_edges[u_id]

                # Check if this was a critical path
                u_is_reachable = (u.distance != math.inf)
                is_critical_path = (v.predecessor == u_id) and u_is_reachable
                if is_critical_path:
                    if old_weight != math.inf:
                        is_critical_path = math.isclose(v.distance, u.distance + old_weight, rel_tol=FLOAT_TOLERANCE)
                    else:
                        is_critical_path = False

                if is_critical_path:
                    print(f"      Path for V({v_id}) was broken! (Old cost: {v.distance:.4f})")
                    # Collect nodes to invalidate. Use tuple to avoid duplicates if same node
                    # is invalidated by multiple deletions.
                    initial_delete_messages.append(Message(u_id, v_id, MessageType.SET_TO_INFINITY, {}))
                    affected_nodes_from_deletes.add(v_id)


        # --- 2. Run ONE combined Invalidation + Addition pass ---
        print(f"\n  --- Batch Phase 1: Invalidation + Addition Pass ---")
        # Add all messages to the queue
        for msg in initial_delete_messages: self.message_queue.append(msg)
        for msg in initial_add_messages: self.message_queue.append(msg)

        self.process_queue() # This will propagate all invalidations and new paths

        # --- 3. Run ONE combined Recomputation pass ---
        print("\n  --- Batch Phase 2: Recomputation Pass ---")
        affected_vertices = []
        for user in self.all_users.values():
            if user.marked_as_infinity:
                user.marked_as_infinity = False
                affected_vertices.append(user)

        # Also include nodes that were *directly* hit by a delete,
        # even if they weren't marked (e.g., if path was already inf)
        for v_id in affected_nodes_from_deletes:
             user = self.all_users.get(v_id)
             if user and user not in affected_vertices:
                  affected_vertices.append(user) # Will query even if not marked

        print(f"    {len(affected_vertices)} unique vertices affected by batch. Querying neighbors...")

        # Enqueue all query messages *first*
        for user in affected_vertices:
            for neighbor_id in user.in_edges.keys():
                 if neighbor_id in self.all_users:
                     self.message_queue.append(Message(user.id, neighbor_id, MessageType.DISTANCE_QUERY, {}))

        # Now, process all queries and subsequent updates until convergence
        self.process_queue()

        end_time = time.perf_counter()
        print("--- Batch update complete. ---")
        return end_time - start_time


    def get_sssp_path_list(self, destination_id):
        """
        Traces the SSSP-Del tree to find the shortest path list from the *active source*.
        Returns a list of user IDs in the path, or None if unreachable/error.
        """
        if not self.source_user_id:
            print("Error: No SSSP source set for get_sssp_path_list.")
            return None
        if destination_id not in self.all_users:
             print(f"Error: Destination {destination_id} not in graph.")
             return None

        user = self.all_users.get(destination_id)
        if not user or user.distance == math.inf: # Add check for user existence
            return None

        path_list = []
        curr = user
        path_len = 0
        # Increased loop protection
        max_path_len = len(self.all_users) + 1
        visited_in_trace = set() # Detect cycles during trace

        while curr is not None and path_len < max_path_len:
            if curr.id in visited_in_trace:
                 print(f"Warning: Cycle detected at {curr.id} during path reconstruction.")
                 return None # Cycle detected
            visited_in_trace.add(curr.id)

            path_list.append(curr.id)
            if curr.id == self.source_user_id:
                break # Found source

            if curr.predecessor is None:
                 # This indicates a potential issue if distance is not inf
                 print(f"Warning: Path reconstruction stopped at {curr.id} with no predecessor, but distance is {curr.distance:.4f}")
                 return None

            if curr.predecessor not in self.all_users:
                 print(f"Warning: Predecessor {curr.predecessor} for user {curr.id} not found in all_users.")
                 return None # Error in path data

            # Check for immediate self-loop cycle
            if curr.predecessor == curr.id:
                 print(f"Warning: Self-loop cycle detected at {curr.id} during path reconstruction.")
                 return None

            curr = self.all_users.get(curr.predecessor) # Use .get() for safety
            path_len += 1

        if path_len >= max_path_len:
             print(f"Warning: Path reconstruction exceeded max length ({max_path_len}) for dest {destination_id}. Potential cycle.")
             return None # Cycle detected or error

        path_list.reverse()

        # Final validation
        if not path_list or path_list[0] != self.source_user_id:
             # print(f"Warning: Path construction failed for dest {destination_id}. Result: {path_list}")
             return None # Error in path construction

        return path_list


    def print_state(self):
        """Prints the SSSP state of all users."""
        if not self.source_user_id:
            print("\n--- No source user set. Please set one with 'source <id>'. ---")
            return

        print(f"\n--- CURRENT SSSP-Del NETWORK STATE (Source: {self.source_user_id}) ---")
        for user_id in sorted(self.all_users.keys()):
            # Handle potential missing user object if loading failed
            user = self.all_users.get(user_id)
            if user:
                 print(user)
            else:
                 print(f"  User(ID: {user_id}) | State: Error - Missing User Object")

        print("--------------------------------------")

    def display_graph(self, title="SSSP-Del Visualization", highlight_dest_id=None):
        """
        Uses NetworkX to visualize the SSSP-Del tree state.
        If highlight_dest_id is provided, it traces and highlights the shortest
        path *within the tree* from the source to that destination.
        Also prints a manual sum check for the highlighted path.
        """
        if not self.source_user_id:
            print("\n--- No source user set for SSSP-Del. Cannot display graph. ---")
            return

        # Create a figure object
        fig = plt.figure(figsize=(14, 10))
        ax = fig.add_subplot(111)

        G = nx.DiGraph()
        spt_edges = []      # Edges in the SSSP tree (not on the highlighted path)
        path_edges = set()  # Edges on the specific highlighted path
        path_nodes = set()  # Nodes on the specific highlighted path
        edge_labels = {}
        node_colors = {} # Use dict for clarity
        node_labels = {}

        # Find the highlighted path using the SSSP-Del tree structure
        highlight_path_list = None
        manual_path_sum = 0.0

        if highlight_dest_id:
            highlight_path_list = self.get_sssp_path_list(highlight_dest_id)
            if highlight_path_list:
                path_nodes = set(highlight_path_list)
                for i in range(len(highlight_path_list) - 1):
                    u_id = highlight_path_list[i]
                    v_id = highlight_path_list[i+1]
                    edge = (u_id, v_id)
                    path_edges.add(edge)

                    # --- MODIFIED: Manually sum the weights along the *actual found path* ---
                    u_node = self.all_users.get(u_id)
                    # Check if edge exists before summing
                    edge_weight = u_node.out_edges.get(v_id) if u_node else None
                    if edge_weight is not None:
                         manual_path_sum += edge_weight
                    else:
                         # This case should ideally not happen if get_sssp_path_list is correct
                         print(f"Warning: Edge {edge} from traced path not found in graph.out_edges for manual sum!")


                # --- MODIFIED: Print the comparison using math.isclose ---
                dest_user = self.all_users.get(highlight_dest_id)
                if dest_user:
                    print("\n--- Path Cost Verification ---")
                    print(f"  SSSP-Del distance for {highlight_dest_id}: {dest_user.distance:.8f}")
                    print(f"  Manual sum of edge weights:      {manual_path_sum:.8f}")
                    # Use math.isclose for robust comparison
                    if not math.isclose(dest_user.distance, manual_path_sum, rel_tol=FLOAT_TOLERANCE * 10): # Slightly larger tolerance for sum
                        print("  WARNING: Costs do not match closely! Check algorithm logic or precision.")
                    else:
                        print("  Costs match within tolerance.")
                    print("------------------------------")

            else:
                 print(f"Note: Cannot highlight path to {highlight_dest_id} (unreachable in SSSP-Del tree).")


        nodes_to_draw = sorted(list(self.all_users.keys()))

        for user_id in nodes_to_draw:
            user = self.all_users.get(user_id)
            if not user: continue # Skip if user somehow missing

            G.add_node(user.id)

            # Display distance with more precision
            dist = 'inf' if user.distance == math.inf else f"{user.distance:.4f}"
            # Ensure username is a string
            username = user.username if isinstance(user.username, str) else f"user_{user_id}"
            node_labels[user.id] = f"{username}\nID: {user.id}\nCost: {dist}"


            # --- CORRECTED COLOR LOGIC ---
            # Set Node Color based on path highlighting - PRIORITIZE SOURCE/DEST
            if user.id == self.source_user_id:
                node_colors[user_id] = 'gold'
            elif highlight_path_list and user.id == highlight_dest_id:
                 node_colors[user_id] = 'lime' # Bright green for destination
            elif user.id in path_nodes: # Check path_nodes AFTER source/dest
                node_colors[user_id] = 'cyan' # Light blue for intermediate path nodes
            elif user.distance == math.inf:
                node_colors[user_id] = '#cccccc' # Gray for unreachable
            else:
                node_colors[user_id] = '#a0cbe2' # Default blue for others in SSSP tree

            # Find SSSP tree edges
            if user.predecessor:
                # Check to prevent drawing a predecessor edge that was deleted
                # Also check predecessor exists
                pred_node = self.all_users.get(user.predecessor)
                # Check if the edge *still exists* in the graph's current state
                if pred_node and user.id in pred_node.out_edges :
                    # Add to SSSP tree edges *only if not* part of the highlighted path
                    if (user.predecessor, user.id) not in path_edges:
                        spt_edges.append((user.predecessor, user.id))

            # Find all graph edges for context
            for target_id, weight in user.out_edges.items():
                # Ensure target node exists before adding edge to NetworkX graph
                 if target_id in self.all_users:
                    G.add_edge(user.id, target_id, weight=weight)
                    # Display edge weight with more precision
                    edge_labels[(user.id, target_id)] = f"{weight:.4f}"

        pos = nx.spring_layout(G, k=2.5, seed=42)

        # --- MODIFIED: Ensure G has nodes before proceeding ---
        if not G.nodes():
             print("Warning: NetworkX graph G has no nodes. Cannot draw.")
             plt.close(fig) # Close the empty figure
             return

        all_graph_edges = list(G.edges()) # Get edges from NetworkX graph object

        # Create final node color list in the order NetworkX expects
        final_node_colors = [node_colors.get(node_id, '#cccccc') for node_id in G.nodes()]


        # --- MODIFIED: Clearer Drawing Order & Arc for Bidirectional ---

        # 1. Draw nodes and labels first
        nx.draw_networkx_nodes(G, pos, node_color=final_node_colors, node_size=3000, edgecolors='black', ax=ax)
        nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=10, ax=ax)

        # 2. Draw all edges (faint gray), use connectionstyle for arcs if bidirectional
        drawn_bidirectional = set() # Keep track to avoid drawing twice
        for u, v in all_graph_edges: # Use edges from G
            # Check for reverse edge
            # Ensure v is in graph before checking G.has_edge(v, u)
            is_bidirectional = v in G and G.has_edge(v, u)
            # Use positive rad for u->v, negative for v->u if bidirectional
            rad = 0.15 if is_bidirectional else 0

            # If it's the reverse edge of an already drawn arc, skip
            if is_bidirectional and (v,u) in drawn_bidirectional:
                continue

            style = f'arc3,rad={rad}' if rad != 0 else 'arc3'

            nx.draw_networkx_edges(G, pos, edgelist=[(u,v)], edge_color='gray',
                                   alpha=0.2, arrows=True, node_size=3000, ax=ax,
                                   connectionstyle=style)

            # Mark the pair as potentially drawn (handle reverse later if needed)
            if is_bidirectional:
                 drawn_bidirectional.add((u,v))
                 # Explicitly draw the reverse arc with opposite curvature
                 # Ensure edge exists before drawing
                 if G.has_edge(v,u):
                    nx.draw_networkx_edges(G, pos, edgelist=[(v,u)], edge_color='gray',
                                        alpha=0.2, arrows=True, node_size=3000, ax=ax,
                                        connectionstyle=f'arc3,rad={-rad}') # Negative rad


        # 3. Draw the SSSP tree (red) - use arcs if needed
        drawn_bidirectional_spt = set()
        for u, v in spt_edges:
             # Ensure u and v are valid nodes before proceeding
             if u not in G or v not in G: continue
             is_bidirectional = G.has_edge(v, u)
             rad = 0.15 if is_bidirectional else 0
             if is_bidirectional and (v,u) in drawn_bidirectional_spt: continue
             style = f'arc3,rad={rad}' if rad != 0 else 'arc3'

             nx.draw_networkx_edges(G, pos, edgelist=[(u,v)], edge_color='red',
                                   width=2.0, alpha=0.8, arrows=True, node_size=3000, ax=ax,
                                   connectionstyle=style)
             if is_bidirectional:
                 drawn_bidirectional_spt.add((u,v))
                 # Draw reverse arc if it's also part of SPT
                 if (v, u) in spt_edges:
                      nx.draw_networkx_edges(G, pos, edgelist=[(v,u)], edge_color='red',
                                            width=2.0, alpha=0.8, arrows=True, node_size=3000, ax=ax,
                                            connectionstyle=f'arc3,rad={-rad}')
                      drawn_bidirectional_spt.add((v,u))


        # 4. Draw the highlighted path (bright green, on top) - use arcs if needed
        drawn_bidirectional_path = set()
        for u, v in path_edges:
             if u not in G or v not in G: continue
             is_bidirectional = G.has_edge(v, u)
             rad = 0.15 if is_bidirectional else 0
             if is_bidirectional and (v,u) in drawn_bidirectional_path: continue
             style = f'arc3,rad={rad}' if rad != 0 else 'arc3'

             nx.draw_networkx_edges(G, pos, edgelist=[(u,v)], edge_color='lime',
                                   width=3.0, arrows=True, node_size=3000, ax=ax,
                                   connectionstyle=style)
             if is_bidirectional:
                 drawn_bidirectional_path.add((u,v))
                 # Draw reverse arc if it's also part of the path
                 if (v, u) in path_edges:
                     nx.draw_networkx_edges(G, pos, edgelist=[(v,u)], edge_color='lime',
                                        width=3.0, arrows=True, node_size=3000, ax=ax,
                                        connectionstyle=f'arc3,rad={-rad}')
                     drawn_bidirectional_path.add((v,u))


        # 5. Draw edge labels (position slightly adjusted for arcs)
        # Use a copy of edge_labels to avoid modifying original during iteration
        labels_to_draw = edge_labels.copy()
        nx.draw_networkx_edge_labels(G, pos, edge_labels=labels_to_draw, font_size=8,
                                     font_color='#333333', ax=ax,
                                     label_pos=0.3, # Adjust label position along edge
                                     bbox=dict(facecolor='white', alpha=0.5, edgecolor='none', boxstyle='round,pad=0.1')) # Add background to labels


        src_name = self.all_users[self.source_user_id].username
        if highlight_dest_id:
          dest_name = self.all_users[highlight_dest_id].username
          ax.set_title(
              f"{title}\nSource: {src_name} (ID {self.source_user_id}) → {dest_name} (ID {highlight_dest_id})",
              fontsize=18
          )
        else:
          ax.set_title(
            f"{title}\nSource: {src_name} (ID {self.source_user_id})",
          fontsize=18
          )
        ax.axis('off')

        # Instead of the blocking plt.show(), use display()
        display(fig)
        plt.close(fig) # Close the figure to prevent memory leaks
        time.sleep(0.1) # Add a small delay to allow Colab I/O to catch up

# ---------------------------------
# 2. Static Dijkstra (Baseline)
# ---------------------------------

def run_static_dijkstra_benchmark(all_users, source_id):
    """
    Runs a full, static Dijkstra algorithm from scratch for benchmarking.
    This is the "naive recompute" baseline. Returns *only* the time.
    """
    if source_id not in all_users:
        return 0.0

    start_time = time.perf_counter()

    distances = {user_id: math.inf for user_id in all_users}
    distances[source_id] = 0
    pq = [(0, source_id)] # (distance, user_id)

    processed_nodes = set() # Avoid reprocessing

    while pq:
        current_distance, u_id = heapq.heappop(pq)

        # Use tolerance and check if already processed
        if u_id in processed_nodes or current_distance > distances[u_id] + FLOAT_TOLERANCE:
            continue
        processed_nodes.add(u_id)

        u = all_users.get(u_id)
        if not u: continue

        for v_id, weight in u.out_edges.items():
            if v_id in distances:
                distance = current_distance + weight
                # Use tolerance
                if distance < distances[v_id] - FLOAT_TOLERANCE:
                    distances[v_id] = distance
                    # Add to heap even if already processed, Dijkstra handles cycles
                    heapq.heappush(pq, (distance, v_id))

    end_time = time.perf_counter()
    return end_time - start_time

def run_static_p2p_path(all_users, source_id, dest_id):
    """
    Runs a static Dijkstra to find a single path from source to destination.
    Returns (time, path, distance).
    """
    if source_id not in all_users or dest_id not in all_users:
        return 0.0, None, math.inf

    start_time = time.perf_counter()

    distances = {user_id: math.inf for user_id in all_users}
    predecessors = {user_id: None for user_id in all_users}
    distances[source_id] = 0

    pq = [(0, source_id)] # (distance, user_id)

    processed_nodes = set() # Add this to prevent reprocessing with stale distances

    path_found = False # Flag to indicate if destination was reached

    while pq:
        current_distance, u_id = heapq.heappop(pq)

        # Optimization: if distance is worse than already found, skip
        if current_distance > distances[u_id] + FLOAT_TOLERANCE:
            continue

        # Optimization: if already processed, skip (important for graphs with cycles)
        if u_id in processed_nodes:
             continue
        processed_nodes.add(u_id)


        # If we've found the destination, we can stop early
        if u_id == dest_id:
            path_found = True
            break

        u = all_users.get(u_id)
        if not u: continue

        for v_id, weight in u.out_edges.items():
            if v_id in distances:
                distance = current_distance + weight
                # Use tolerance
                if distance < (distances[v_id] - FLOAT_TOLERANCE):
                    distances[v_id] = distance
                    predecessors[v_id] = u_id
                    heapq.heappush(pq, (distance, v_id))

    end_time = time.perf_counter()
    d_time = end_time - start_time

    # Reconstruct path only if destination was reached
    path = []
    if path_found and distances[dest_id] != math.inf:
        curr = dest_id
        path_len = 0
        max_path_len = len(all_users) + 1
        visited_in_trace = set() # Cycle detection for reconstruction

        while curr is not None and path_len < max_path_len:
            if curr in visited_in_trace:
                 print(f"Warning: Cycle detected at {curr} during Dijkstra path reconstruction.")
                 return d_time, None, math.inf
            visited_in_trace.add(curr)

            path.append(str(curr))
            if curr == source_id:
                 break # Reached source

            pred = predecessors.get(curr)
            if pred is None:
                 if curr != source_id:
                     print(f"Warning: Dijkstra path reconstruction broke at {curr}. Predecessor map entry missing or None.")
                     return d_time, None, math.inf # Error in path
                 else:
                     break # Reached source correctly

            curr = pred
            path_len += 1

        if path_len >= max_path_len:
            print(f"Warning: Dijkstra path reconstruction exceeded max length ({max_path_len}) for dest {dest_id}. Potential cycle.")
            return d_time, None, math.inf # Cycle or error

        path.reverse()

        # Final validation
        if not path or int(path[0]) != source_id:
            #print(f"Warning: Dijkstra path construction failed for dest {dest_id}. Result: {path}")
            return d_time, None, math.inf # Path not found

        return d_time, path, distances[dest_id]
    else:
        # Destination was not reached or distance is still infinity
        return d_time, None, math.inf


# ---------------------------------
# 3. Benchmarking
# ---------------------------------

def plot_benchmark(results):
    """Plots the performance comparison graph."""
    if not results:
        print("\nNo benchmark data to plot. Run 'add' or 'delete' commands first.")
        return

    df = pd.DataFrame(results)

    # Create a figure and axes object
    fig, ax = plt.subplots(figsize=(12, 7))

    ax.plot(df['event_id'], df['sssp_del_time'], 'o-', label='SSSP-Del (Your Algo)', color='blue')
    ax.plot(df['event_id'], df['dijkstra_time'], 's-', label='Static Dijkstra (Re-compute)', color='red')

    ax.set_yscale('log')
    ax.set_xlabel('Event Number', fontsize=14)
    ax.set_ylabel('Time Taken (seconds, log scale)', fontsize=14)
    ax.set_title('SSSP-Del vs. Static Dijkstra Performance', fontsize=16)
    ax.legend(fontsize=12)
    ax.grid(True, which="both", ls="--", alpha=0.5)

    # Instead of the blocking plt.show(), use display()
    display(fig)
    plt.close(fig) # Close the figure to prevent memory leaks
    time.sleep(0.1) # Add a small delay to allow Colab I/O to catch up

# ---------------------------------
# 4. Main Interactive Simulation
# ---------------------------------

if __name__ == "__main__":
    CSV_FILE = "social_engagement_5_users.csv"
    df = None # Initialize df
    try:
        df = pd.read_csv(CSV_FILE)
        print(f"Successfully loaded '{CSV_FILE}'. {len(df)} edges found.")
    except FileNotFoundError:
        print(f"ERROR: '{CSV_FILE}' not found. Cannot proceed without data.")
        # Exit if the file isn't found, as fallback was removed.
        exit()
    except Exception as e:
         print(f"Error loading CSV: {e}. Cannot proceed.")
         exit()

    g = SSSPGraph()
    g.load_users_from_df(df)
    g.load_edges_from_df(df)

    benchmark_results = []
    event_counter = 0

    print("\n--- SSSP-Del Interactive Simulation ---")
    print("Commands:")
    print("  source <user_id>    - (For Benchmark) Set source for SSSP-Del (e.g., 'source 101')")
    print("  path <src_id> <dest_id> - (For Query) Find shortest path (e.g., 'path 101 105')")
    print("  add <u_id> <v_id> <w> - Add a new edge & benchmark (e.g., 'add 101 105 0.1')")
    print("  delete <u_id> <v_id>  - Delete an edge & benchmark (e.g., 'delete 101 102')")
    print("  batch <filename>    - Process a CSV batch of 'add'/'delete' ops ")
    print("  state               - Print SSSP-Del state of all users (from active source)")
    print("  searchname <username> - Find closest user with that name and show path")
    print("  viz [dest_id]       - Visualize SSSP-Del tree. Optionally highlight path to <dest_id> (e.g., 'viz 105')")
    print("  plot                - Show the benchmark performance plot")
    print("  help                - Show this menu")
    print("  quit                - Exit the simulation")
    print("-----------------------------------------")


    while True:
        # We separate the input() call from the command processing
        # to make the loop more stable in a notebook environment.
        cmd_str = ""
        try:
            cmd_str = input("\nEnter command: ").strip().lower()
            if not cmd_str:
                continue
        except (EOFError, KeyboardInterrupt):
            print("\nExiting simulation.")
            break

        # Now, we process the command in a separate try...except block
        try:
            cmd = cmd_str.split()
            command = cmd[0]

            if command == "quit" or command == "exit":
                print("Exiting simulation.")
                break

            elif command == "help":
                print("\nCommands:")
                print("  source <user_id>    - (For Benchmark) Set source for SSSP-Del (e.g., 'source 101')")
                print("  path <src_id> <dest_id> - (For Query) Find shortest path (e.g., 'path 101 105')")
                print("  add <u_id> <v_id> <w> - Add a new edge & benchmark (e.g., 'add 101 105 0.1')")
                print("  delete <u_id> <v_id>  - Delete an edge & benchmark (e.g., 'delete 101 102')")
                print("  batch <filename>    - Process a CSV batch of 'add'/'delete' ops (e.g., 'batch batch_changes.csv')")
                print("  state               - Print SSSP-Del state of all users (from active source)")
                print("  searchname <username> - Find closest user with that name and show path")
                print("  viz [dest_id]       - Visualize SSSP-Del tree. Optionally highlight path to <dest_id> (e.g., 'viz 105')")
                print("  plot                - Show the benchmark performance plot")
                print("  help                - Show this menu")
                print("  quit                - Exit the simulation")

            elif command == "source":
                source_id = int(cmd[1])
                g.set_source(source_id)
                g.print_state()

            elif command == "path":
                source_id = int(cmd[1])
                dest_id = int(cmd[2])

                # Run the static P2P Dijkstra
                d_time, path_list, distance = run_static_p2p_path(g.all_users, source_id, dest_id)

                if path_list:
                    print(f"\n--- Static Dijkstra Path from {source_id} to {dest_id} ---")
                    print(f"  Path: {' -> '.join(path_list)}")
                    print(f"  Total Cost: {distance:.4f}")
                    print(f"  (Calculation time: {d_time:.8f}s)")
                else:
                    print(f"--- No path found from {source_id} to {dest_id} ---")

            elif command == "add":
                if not g.source_user_id:
                    print("Error: Please set a source user first with 'source <id>'.")
                    continue
                u_id, v_id, weight = int(cmd[1]), int(cmd[2]), float(cmd[3])

                # 1. Benchmark SSSP-Del
                sssp_del_time = g.simulate_edge_add(u_id, v_id, weight)

                # 2. Benchmark Static Dijkstra
                dijkstra_time = run_static_dijkstra_benchmark(g.all_users, g.source_user_id)

                event_counter += 1
                benchmark_results.append({
                    'event_id': event_counter,
                    'type': 'add',
                    'sssp_del_time': sssp_del_time,
                    'dijkstra_time': dijkstra_time
                })
                print(f"  Benchmark: SSSP-Del took {sssp_del_time:.8f}s | Static Dijkstra took {dijkstra_time:.8f}s")
                g.print_state()
            elif command == "searchname":
              if len(cmd) < 2:
                  print("Usage: searchname <username>")
                  continue

              username = " ".join(cmd[1:])  # support multi-word names

              uid, dist, path = g.find_user_by_name(username)

              if uid is not None:
                  print(f"\nClosest user with name '{username}': User ID {uid}")

                  if dist == math.inf:
                      print("This user is NOT reachable from the current source.")
                      print("Showing entire graph anyway...")
                  else:
                      print(f"Distance from source: {dist:.4f}")
                      if path:
                        print("Path:", " -> ".join(str(x) for x in path))
                      else:
                          print("No reachable path from the source.")

                  # 🔥 NEW: Automatically show visualization
                  print("\n📌 Visualizing path to this user...")
                  g.display_graph(
                      title=f"SSSP-Del Graph: Path to '{username}'",
                      highlight_dest_id=uid
                  )

              else:
                  print(f"No user found with name '{username}'.")
            elif command == "delete":
                if not g.source_user_id:
                    print("Error: Please set a source user first with 'source <id>'.")
                    continue
                u_id, v_id = int(cmd[1]), int(cmd[2])

                # 1. Benchmark SSSP-Del
                sssp_del_time = g.simulate_edge_break(u_id, v_id)

                # 2. Benchmark Static Dijkstra
                dijkstra_time = run_static_dijkstra_benchmark(g.all_users, g.source_user_id)

                event_counter += 1
                benchmark_results.append({
                    'event_id': event_counter,
                    'type': 'delete',
                    'sssp_del_time': sssp_del_time,
                    'dijkstra_time': dijkstra_time
                })
                print(f"  Benchmark: SSSP-Del took {sssp_del_time:.8f}s | Static Dijkstra took {dijkstra_time:.8f}s")
                g.print_state()

            elif command == "batch":
                if not g.source_user_id:
                    print("Error: Please set a source user first with 'source <id>'.")
                    continue

                batch_filename = cmd[1]
                try:
                    batch_df = pd.read_csv(batch_filename)
                    print(f"Successfully loaded batch file '{batch_filename}'.")
                except FileNotFoundError:
                    print(f"ERROR: Batch file '{batch_filename}' not found.")
                    print("Please run 'generate_batch_file.py' first.")
                    continue
                except Exception as e:
                    print(f"Error reading batch file: {e}")
                    continue

                # 1. Benchmark SSSP-Del (Batch Novelty)
                sssp_del_time = g.simulate_batch_update(batch_df)

                # 2. Benchmark Static Dijkstra
                dijkstra_time = run_static_dijkstra_benchmark(g.all_users, g.source_user_id)

                event_counter += 1
                benchmark_results.append({
                    'event_id': event_counter,
                    'type': 'batch',
                    'sssp_del_time': sssp_del_time,
                    'dijkstra_time': dijkstra_time
                })
                print(f"  Benchmark: SSSP-Del Batch took {sssp_del_time:.8f}s | Static Dijkstra took {dijkstra_time:.8f}s")
                g.print_state()


            elif command == "state":
                g.print_state()

            elif command == "viz":
                if not g.source_user_id:
                    print("Error: Please set a source user first with 'source <id>'.")
                    continue

                highlight_dest_id = None
                if len(cmd) > 1:
                    try:
                        highlight_dest_id = int(cmd[1])
                        if highlight_dest_id not in g.all_users:
                            print(f"Error: Destination user {highlight_dest_id} not found.")
                            continue
                    except ValueError:
                        print("Error: Invalid destination ID. Use 'viz <id>'.")
                        continue

                g.display_graph(f"SSSP-Del Tree (Source: {g.source_user_id})",
                                highlight_dest_id=highlight_dest_id)

            elif command == "plot":
                plot_benchmark(benchmark_results)

            else:
                print("Error: Unknown command. Type 'help' for a list of commands.")

        except IndexError:
            print("Error: Invalid arguments. Type 'help' for command usage.")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")